Basic Material Object Implementation
treydinges/brlcad pull request #1
Opened 2021-10-03 21:46 UTC by treydinges

2021-10-26 17:12 UTC, cdconn00 approved these changes

2021-10-26 17:38 UTC, cdconn00 requested changes
Can you fix the mem leaks in material.c?

2021-10-26 18:02 UTC, treydinges commented on src/libbu/avs.c
> +    const char * attributes = bu_vls_strgrab(&str);
strgrab is destructive so we don't need to free str here

2021-10-27 00:20 UTC, cdconn00 approved these changes

2021-10-28 16:53 UTC, apstudwell approved these changes

2021-10-28 16:55 UTC, merged